### ISSUE TITLE
how u build this?

### ISSUE THREAD

**Issue by crosbymichael** [stevvooe/continuity#36]
I see there is a makefile but `make` does not work and go build gives me 

```bash
go build
# github.com/stevvooe/continuity
./context.go:383: undefined: atomicWriteFile
```

**Comment by stevvooe** [comment]
Looks like we merged a PR missing a check. We'll need to add CI to this project to avoid this in the future.

**Comment by stevvooe** [comment]
Looks like it was https://github.com/stevvooe/continuity/pull/35.
