### ISSUE TITLE
[Suggestion] CAS representation for alternative data stream

### ISSUE THREAD

**Issue by AkihiroSuda** [stevvooe/continuity#47]
```pb
message Resource {
  ..
  // Ads stores one or more alternate data streams for the target resource.
  map<string, bytes> ads = 13;
}
```

In current design, the representation of ADS is likely to become so huge, because it contains the full data of ADS.

So WDYT about adding CAS representation for ADS?
i.e.
```pb
message Resource {
  ..
  // Ads stores one or more alternate data streams for the target resource.
  map<string, bytes> ads = 13;
  // AdsDigests stores digests of one or more alternate data streams for the target resource.
  // How to access the actual data using the digest is not defined.
  // Intersection of Ads and AdsDigests SHOULD be an empty set.
  map<string, string> ads_digests = 14;
}
```

**Comment by stevvooe** [comment]
I'd prefer an representation with a submessage, rather than a map. Something like this maybe:

```
message ADSEntry {
  string name;
  bytes data;
  string digest;
}
```

I am fairly unfamiliar with ADS. These are mostly there to demonstrate that continuity has the capability to be multi-platform.

Thanks for the feedback here!

**Comment by stevvooe** [comment]
@AkihiroSuda The message break out was done in https://github.com/stevvooe/continuity/pull/57. If you want to add digest support, let me know!

**Comment by AkihiroSuda** [comment]
Sure, https://github.com/stevvooe/continuity/pull/58
