### ISSUE TITLE
Make `mode` optional?

### ISSUE THREAD

**Issue by AkihiroSuda** [stevvooe/continuity#48]
https://github.com/stevvooe/continuity/blob/master/proto/manifest.proto

Since `mode` is currently defined as `uint32`, there is no way to omit `mode` from the manifest
(zero should be interpreted as zero, not nil)

Or maybe it should bbetter to clarify that `mode` is mandatory field and cannot be omitted, but I'm not sure it causes compatibility issue

**Comment by stevvooe** [comment]
Fields in proto3 cannot be optional. Mode is required.

Is there a use case for not specifying the file mode?

**Comment by AkihiroSuda** [comment]
My intent was for the root dir issue discussed in https://github.com/docker/containerd/issues/523, but on second thought I found that the `ModeDir` bit is still required.
So I'm closing this issue.

However, for `context.Verify()`, I think we still need some umask-like feature for the issue mentioned above and for non-UNIX filesystems such as FAT.

**Comment by stevvooe** [comment]
> However, for context.Verify(), I think we still need some umask-like feature for the issue mentioned above and for non-UNIX filesystems such as FAT.

Could you clarify that request in another issue?

**Comment by AkihiroSuda** [comment]
sure, opened https://github.com/stevvooe/continuity/issues/49
